window.PulseDeckData = {
  projects: [
    {
      id: "i-5986",
      stip: "I-5986",
      contract: "C204800",
      division: 6,
      route: "I-95",
      county: "Robeson",
      description: "Widening and bridge rehabilitation near Lumberton",
      contractor: "Flatiron Branch Civil JV",
      awardAmount: 403.8,
      currentEstimate: 289.2,
      physical: 71,
      status: "Active / On Schedule",
      dates: {
        letting: "Jan 18, 2024",
        award: "Feb 21, 2024",
        completion: "Nov 12, 2027",
        estimate: "May 31, 2026",
      },
      contact: { name: "Angela McRae, PE", phone: "(910) 486-1234" },
      ncdotUrl: "https://www.ncdot.gov/projects/i-95-widening/Pages/default.aspx",
    },
    {
      id: "r-5700",
      stip: "R-5700",
      contract: "C204775",
      division: 5,
      route: "NC 540",
      county: "Wake",
      description: "Interchange and corridor improvements near Raleigh",
      contractor: "Blythe Construction Inc.",
      awardAmount: 212,
      currentEstimate: 137.4,
      physical: 63,
      status: "Under Review",
      dates: {
        letting: "Sep 19, 2023",
        award: "Oct 24, 2023",
        completion: "Aug 18, 2026",
        estimate: "Jun 7, 2026",
      },
      contact: { name: "Marcus Benton", phone: "(919) 707-2400" },
      ncdotUrl: "https://www.ncdot.gov/projects/complete-540/Pages/default.aspx",
    },
    {
      id: "u-6039",
      stip: "U-6039",
      contract: "C204920",
      division: 10,
      route: "I-485 / US 74",
      county: "Mecklenburg",
      description: "Managed lanes and interchange upgrades",
      contractor: "Lane Construction Corporation",
      awardAmount: 318.6,
      currentEstimate: 152.9,
      physical: 48,
      status: "Active / On Schedule",
      dates: {
        letting: "Mar 12, 2024",
        award: "Apr 16, 2024",
        completion: "Feb 27, 2028",
        estimate: "May 31, 2026",
      },
      contact: { name: "Tiffany Caldwell, PE", phone: "(704) 983-4400" },
      ncdotUrl: "https://www.ncdot.gov/projects/us-74-express-lanes/Pages/default.aspx",
    },
    {
      id: "i-2513aa",
      stip: "I-2513AA",
      contract: "C204600",
      division: 13,
      route: "I-26",
      county: "Buncombe",
      description: "Asheville connector structures and retaining walls",
      contractor: "Archer Western Construction",
      awardAmount: 147.5,
      currentEstimate: 126.3,
      physical: 82,
      status: "Delayed / Behind Schedule",
      dates: {
        letting: "Jun 20, 2022",
        award: "Jul 27, 2022",
        completion: "Dec 19, 2026",
        estimate: "Jun 7, 2026",
      },
      contact: { name: "Daniel Pressley", phone: "(828) 250-3000" },
      ncdotUrl: "https://www.ncdot.gov/projects/asheville-i-26-connector/Pages/default.aspx",
    },
    {
      id: "r-2633ba",
      stip: "R-2633BA",
      contract: "C204501",
      division: 3,
      route: "US 17",
      county: "New Hanover",
      description: "Hampstead bypass grading, drainage, and bridges",
      contractor: "Barnhill Contracting Company",
      awardAmount: 185.2,
      currentEstimate: 169.6,
      physical: 93,
      status: "Completed / Final Estimate",
      dates: {
        letting: "Nov 15, 2021",
        award: "Dec 21, 2021",
        completion: "Apr 30, 2026",
        estimate: "May 31, 2026",
      },
      contact: { name: "Eleanor Wilkes", phone: "(910) 341-2000" },
      ncdotUrl: "https://www.ncdot.gov/projects/us-17-hampstead-bypass/Pages/default.aspx",
    },
    {
      id: "b-5642",
      stip: "B-5642",
      contract: "C204845",
      division: 1,
      route: "NC 12",
      county: "Dare",
      description: "Dune stabilization and bridge preservation on Hatteras Island",
      contractor: "S.T. Wooten Corporation",
      awardAmount: 64.9,
      currentEstimate: 31.1,
      physical: 46,
      status: "Active / On Schedule",
      dates: {
        letting: "Dec 13, 2023",
        award: "Jan 17, 2024",
        completion: "Sep 15, 2026",
        estimate: "Jun 7, 2026",
      },
      contact: { name: "Heather Twiddy", phone: "(252) 482-1850" },
      ncdotUrl: "https://www.ncdot.gov/projects/nc-12-south/Pages/default.aspx",
    },
  ],
  activities: [
    {
      title: "HiCAMS nightly sync completed",
      detail: "Six active contracts refreshed with estimate, payment, and milestone data.",
      time: "Jun 10, 2026 at 2:15 AM ET",
      tone: "green",
    },
    {
      title: "Estimate #18 posted for I-5986",
      detail: "Physical progress advanced to 71% after girder installation and shoulder drainage work.",
      time: "Jun 9, 2026 at 4:40 PM ET",
      tone: "blue",
    },
    {
      title: "Scope review opened for R-5700",
      detail: "Utility relocation variance moved the Raleigh package into amber review.",
      time: "Jun 9, 2026 at 11:25 AM ET",
      tone: "amber",
    },
    {
      title: "Delay flag escalated on I-2513AA",
      detail: "Retaining wall sequencing and weather impacts pushed the Asheville connector behind baseline.",
      time: "Jun 8, 2026 at 3:18 PM ET",
      tone: "red",
    },
    {
      title: "Final estimate routed for R-2633BA",
      detail: "Hampstead bypass package entered closeout review after substantial completion.",
      time: "Jun 6, 2026 at 9:05 AM ET",
      tone: "gray",
    },
  ],
  statusMeta: {
    "Active / On Schedule": {
      short: "On Schedule",
      className: "status-positive",
      gauge: "#146c2e",
      tone: "success",
    },
    "Under Review": {
      short: "At Risk",
      className: "status-warning",
      gauge: "#855300",
      tone: "warning",
    },
    "Delayed / Behind Schedule": {
      short: "Delayed",
      className: "status-critical",
      gauge: "#b3261e",
      tone: "critical",
    },
    "Completed / Final Estimate": {
      short: "Final Estimate",
      className: "status-muted",
      gauge: "#747775",
      tone: "neutral",
    },
  },
};
